import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CategorySection from "../components/Items/CategorySection";
import ProgressBar from "../components/Statistics/ProgressBar";
import s from "../styles/Home.module.css";

const Main: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <h1>
          <span className={s.orangeText}>Shoppingify</span> allows you take your
          shopping list wherever you go
        </h1>

        <section className={s.content}>
          <CategorySection
            title="Meat and Fish"
            items={["Chicken leg box", "Chicken 1kg"]}
          />

          <ProgressBar progress={20} />

          <CategorySection
            title="Fruit and vegetables"
            items={[
              "Acocado",
              "Banana",
              "Pre-cooked corn 450g",
              "Mandarin Nadorcott",
              "Acocado",
              "Banana",
            ]}
          />

          {/* <section className={styles.cards}>
            <ItemCard>Acocado</ItemCard>
            <ItemCard>Banana</ItemCard>
            <ItemCard>Pre-cooked corn 450g</ItemCard>
            <ItemCard>Mandarin Nadorcott</ItemCard>
            <ItemCard>Mandarin Nadorcott</ItemCard>
          </section> */}
        </section>
      </main>

      <footer className={s.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={s.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Main;
