import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import CategorySection from "../components/Items/CategorySection";
import ItemCard from "../components/Items/ItemCard";
import styles from "../styles/Home.module.css";

const Main: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <section>
          <header>
            <h2>Fruit and vegetables</h2>
          </header>

          <CategorySection
            title="Meat and Fish"
            items={["Chicken leg box", "Chicken 1kg"]}
          />

          <section className={styles.cards}>
            <ItemCard>Acocado</ItemCard>
            <ItemCard>Banana</ItemCard>
            <ItemCard>Pre-cooked corn 450g</ItemCard>
            <ItemCard>Mandarin Nadorcott</ItemCard>
            <ItemCard>Mandarin Nadorcott</ItemCard>
          </section>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Main;
