import type { NextPage } from "next";
import Head from "next/head";
import ProgressBar from "@/components/Statistics/ProgressBar";
import s from "@/styles/Home.module.css";

const Main: NextPage = () => {
  return (
    <div className={s.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <section className={s.content}>
          <div>
            <div className={s.textContainer}>
              <p>Banana</p>
              <p>12%</p>
            </div>
            <ProgressBar progress={20} />
          </div>
        </section>
      </main>
    </div>
  );
};

export default Main;
